[package]
name = "bcl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = "0.4.41"
directories = "6.0.0"
indexmap = "2.13.0"
lazy-regex = "3.6.0"
owo-colors = "4.2.2"
rusqlite = {version = "0.37.0", features = ["chrono"]}
serde = { version = "1", features = ["derive"] }
tabled = "0.20.0"
tempfile = "3.21.0"
toml = "0.8"
